---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'

SiteConfig:
  extensions:
    - SiteConfig_Extension
Block:
  extensions:
    - ContentBlock_Extension

BlockManager:
  themes:
    simple: 
      areas:
        AfterContent: true
        BeforeContent: true